name: wailord-assets
services:
  nginx: 
    image: nginxinc/nginx-unprivileged
    ports:
      - "80:80"
    volumes:
      - ./assets:/var/www/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always